[package]
name = "ellie"
version = "0.1.0"
edition = "2021"
license = "MIT"

authors = ["Felipe S. S. Schneider <schneider.felipe.5@gmail.com>"]
description = "Urban broccoli"
repository = "https://github.com/schneiderfelipe/ellie"
documentation = "https://docs.rs/ellie"
rust-version = "1.56.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.14.0"
