[[function]]
name = "get_current_weather"
description = "Get the current weather in a given location"

[function.parameters]
type = "object"
required = ["location"]

[function.parameters.properties.location]
type = "string"
description = "The city and state, e.g. San Francisco, CA"

[function.parameters.properties.unit]
type = "string"
enum = ["celsius", "fahrenheit"]

[function.provider]
command = "weather"
args = ["current"]
